AllCops:
  Exclude:
    - 'sbin/*'
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false