FROM ruby:2.6.0-alpine3.8

MAINTAINER liubaicai "liushuai.baicai@hotmail.com"

WORKDIR /galle

COPY . /galle

RUN mkdir /galledata

RUN apk add --no-cache alpine-sdk\
    sqlite-dev bash curl tzdata git openssh-client &&\
    bundle install --without development test &&\
    apk del alpine-sdk

ENV RAILS_SERVE_STATIC_FILES=true PORT=80 SQLITE3=/galledata/db/db.sqlite3 SSH_KEY_PATH=/galledata/ssh

CMD ["bash", "galle", "start-docker"]
