#!/usr/bin/env bash

start() {
    rvm use 2.6.0 do ruby sbin/puma -d -C config/puma-deploy.rb
    echo "=== puma startup: $(date +'%Y-%m-%d %H:%M:%S %z') ==="
}

stop() {
    test -e tmp/pids/puma.pid && {
        kill -9 `cat tmp/pids/puma.pid`
        rm tmp/pids/puma.pid
        echo "=== puma shutdown: $(date +'%Y-%m-%d %H:%M:%S %z') ==="
    }
}

install() {
    if type rvm >/dev/null 2>&1; then
        rvm requirements
        rvm install 2.6.0
        rvm use 2.6.0 do bundle install
        rvm use 2.6.0 do rails db:migrate RAILS_ENV=production
        rvm use 2.6.0 do rails db:seed RAILS_ENV=production
        rvm use 2.6.0 do rails assets:precompile
    else
        echo >&2 "I require rvm but it's not installed.  Aborting.";
        echo >&2 "Install RVM:";
        echo >&2 "   \"curl -sSL https://get.rvm.io | bash -s stable --ruby=2.6.0\"";
        exit 1;
    fi
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    install)
        install
        ;;
    *)
        echo "Usage: galle {start|stop|restart|install}"
        exit 1
        ;;
esac
